### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by TendTo** [nucats-soc/manor#2]
Adding support for a containerized version of the software will allow for an easier means to deploy the bot on many different systems, with the only requirement being a version of Docker. Furthermore, a docker-compose setup would take care of the database needs of the bot without requiring any complex setup.

### Subtasks
- [ ] make so the configuration can be changed easily through the environment variable, as that is the standard way of configuring containers
- [ ] introduce a Dockerfile and a docker-compose file
- [ ] improve the database interface

**Comment by amnexya** [comment]
Docker support added in rewrite, closing issue.
